name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pull OWASP ZAP Docker Image
        run: docker pull owasp/zap2docker-stable

      - name: Run ZAP Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw owasp/zap2docker-stable zap-full-scan.py \
          -t http://localhost:3000 -r zap_scan_report.html

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: zap_scan_report.html
